version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-skillsync}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-skillsyncpass}
      POSTGRES_DB: ${POSTGRES_DB:-skillsyncdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
